"""add cover_image_url to blog_post

Revision ID: 04ca95d888fc
Revises: b6af94f28712
Create Date: 2026-06-29 10:18:55.519037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04ca95d888fc'
down_revision = 'b6af94f28712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_column('cover_image_url')

    # ### end Alembic commands ###
