"""add email change confirmation columns

Revision ID: 08d9189bacbd
Revises: 32c973a6fcc2
Create Date: 2026-06-26 08:44:06.507187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08d9189bacbd'
down_revision = '32c973a6fcc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_email', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('email_change_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('email_change_expiration', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_email_change_token'), ['email_change_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email_change_token'))
        batch_op.drop_column('email_change_expiration')
        batch_op.drop_column('email_change_token')
        batch_op.drop_column('pending_email')

    # ### end Alembic commands ###
