"""add notification and user_follow models

Revision ID: 12036720d06b
Revises: a3f1d2c9e5b7
Create Date: 2026-06-17 08:56:38.129797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12036720d06b'
down_revision = 'a3f1d2c9e5b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notif_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=True),
    sa.Column('link', sa.String(length=512), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('job_uuid', sa.String(length=36), nullable=True),
    sa.Column('job_status', sa.String(length=16), nullable=True),
    sa.Column('job_progress', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_job_uuid'), ['job_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_notif_type'), ['notif_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    op.create_table('user_follow',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'followed_id', name='uq_user_follow')
    )
    with op.batch_alter_table('user_follow', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_follow_followed_id'), ['followed_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_follow_follower_id'), ['follower_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_follow', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_follow_follower_id'))
        batch_op.drop_index(batch_op.f('ix_user_follow_followed_id'))

    op.drop_table('user_follow')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_notif_type'))
        batch_op.drop_index(batch_op.f('ix_notification_job_uuid'))
        batch_op.drop_index(batch_op.f('ix_notification_is_read'))
        batch_op.drop_index(batch_op.f('ix_notification_created_at'))

    op.drop_table('notification')
    # ### end Alembic commands ###
