"""add rule_relation table

Revision ID: 19a3cbae6794
Revises: 9bbf0463e0bb
Create Date: 2026-09-14 08:58:00.645548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a3cbae6794'
down_revision = '9bbf0463e0bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: hand-trimmed — autogenerate also proposed dropping 8 pre-existing
    # pg_trgm GIN indexes on `rule` (author/description/format/original_uuid/
    # source/title/to_string/uuid). Those were created manually (see
    # migrations/versions/abd5af3fd65a_add_pg_trgm_gin_index_on_rule_source_.py
    # and siblings) and aren't declared on the SQLAlchemy model, so alembic
    # always misreads them as "removed" — dropping them here would silently
    # gut Rule's trigram search performance. This migration only ever
    # intended to add the new rule_relation table.
    op.create_table('rule_relation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('source_rule_id', sa.Integer(), nullable=False),
    sa.Column('target_rule_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=32), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('source_rule_id != target_rule_id', name='ck_rule_relation_no_self_link'),
    sa.ForeignKeyConstraint(['source_rule_id'], ['rule.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_rule_id'], ['rule.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_rule_id', 'target_rule_id', 'relation_type', name='uq_rule_relation_pair_type')
    )
    with op.batch_alter_table('rule_relation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_relation_source_rule_id'), ['source_rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_relation_target_rule_id'), ['target_rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_relation_uuid'), ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_relation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_relation_uuid'))
        batch_op.drop_index(batch_op.f('ix_rule_relation_target_rule_id'))
        batch_op.drop_index(batch_op.f('ix_rule_relation_source_rule_id'))

    op.drop_table('rule_relation')
    # ### end Alembic commands ###
