"""add attack_technique and rule_attack_association

Revision ID: 2135280c127e
Revises: a78167451235
Create Date: 2026-06-24 14:25:31.456677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2135280c127e'
down_revision = 'a78167451235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attack_technique',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('technique_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('tactic_keys', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('is_subtechnique', sa.Boolean(), nullable=True),
    sa.Column('parent_technique_id', sa.String(length=20), nullable=True),
    sa.Column('deprecated', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attack_technique', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attack_technique_technique_id'), ['technique_id'], unique=True)

    op.create_table('rule_attack_association',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('technique_id', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], ),
    sa.ForeignKeyConstraint(['technique_id'], ['attack_technique.technique_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'technique_id', name='uq_rule_attack_technique')
    )
    with op.batch_alter_table('rule_attack_association', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_attack_association_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_attack_association', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_attack_association_uuid'))

    op.drop_table('rule_attack_association')
    with op.batch_alter_table('attack_technique', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attack_technique_technique_id'))

    op.drop_table('attack_technique')
    # ### end Alembic commands ###
