"""add is_dangerous and danger_description to rule_test

Revision ID: 22560ae69b74
Revises: e6cfde86ee6f
Create Date: 2026-07-02 14:15:51.659358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22560ae69b74'
down_revision = 'e6cfde86ee6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_dangerous', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('danger_description', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_rule_test_is_dangerous'), ['is_dangerous'], unique=False)
        batch_op.alter_column('is_dangerous', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_test', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_test_is_dangerous'))
        batch_op.drop_column('danger_description')
        batch_op.drop_column('is_dangerous')

    # ### end Alembic commands ###
