"""add unified report model

Revision ID: 2320e80f2f0c
Revises: dc9725647a6f
Create Date: 2026-06-24 10:51:08.598313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '2320e80f2f0c'
down_revision = 'dc9725647a6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    tables = inspector.get_table_names()
    if 'report' not in tables:
        op.create_table('report',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('object_type', sa.String(length=20), nullable=False),
        sa.Column('object_id', sa.Integer(), nullable=False),
        sa.Column('reason', sa.String(length=100), nullable=False),
        sa.Column('message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('report', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_report_created_at'), ['created_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_report_object_id'), ['object_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_report_object_type'), ['object_type'], unique=False)
            batch_op.create_index(batch_op.f('ix_report_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    tables = inspector.get_table_names()
    if 'report' in tables:
        with op.batch_alter_table('report', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_report_status'))
            batch_op.drop_index(batch_op.f('ix_report_object_type'))
            batch_op.drop_index(batch_op.f('ix_report_object_id'))
            batch_op.drop_index(batch_op.f('ix_report_created_at'))

        op.drop_table('report')
    # ### end Alembic commands ###
