"""add ip_address to registered_instance

Revision ID: 2337748f9558
Revises: 08d9189bacbd
Create Date: 2026-06-29 08:17:12.732400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2337748f9558'
down_revision = '08d9189bacbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registered_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registered_instance', schema=None) as batch_op:
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###
