"""add is_draft to blog_post

Revision ID: 26c14494c172
Revises: e43f7931ee0c
Create Date: 2026-06-29 09:10:29.125093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c14494c172'
down_revision = 'e43f7931ee0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_draft', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_blog_post_is_draft'), ['is_draft'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_post_is_draft'))
        batch_op.drop_column('is_draft')

    # ### end Alembic commands ###
