"""add soft delete to Rule

Revision ID: 31e4523a751b
Revises: 19550901f18b
Create Date: 2026-06-01 14:23:17.763580

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '31e4523a751b'
down_revision = '19550901f18b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    rule_cols = {c['name'] for c in inspector.get_columns('rule')}
    if 'is_deleted' not in rule_cols:
        with op.batch_alter_table('rule', schema=None) as batch_op:
            batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
            batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
            batch_op.add_column(sa.Column('deleted_by_id', sa.Integer(), nullable=True))
            batch_op.add_column(sa.Column('delete_batch_uuid', sa.String(length=36), nullable=True))
            batch_op.create_index(batch_op.f('ix_rule_delete_batch_uuid'), ['delete_batch_uuid'], unique=False)
            batch_op.create_index(batch_op.f('ix_rule_is_deleted'), ['is_deleted'], unique=False)
            batch_op.create_foreign_key(None, 'user', ['deleted_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    rule_cols = {c['name'] for c in inspector.get_columns('rule')}
    if 'is_deleted' in rule_cols:
        with op.batch_alter_table('rule', schema=None) as batch_op:
            batch_op.drop_constraint(None, type_='foreignkey')
            batch_op.drop_index(batch_op.f('ix_rule_is_deleted'))
            batch_op.drop_index(batch_op.f('ix_rule_delete_batch_uuid'))
            batch_op.drop_column('delete_batch_uuid')
            batch_op.drop_column('deleted_by_id')
            batch_op.drop_column('deleted_at')
            batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
