"""add pref_blog_published to notification_preference

Revision ID: 3f50a4df5251
Revises: 8bfe97bb0eee
Create Date: 2026-06-29 13:10:41.402768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f50a4df5251'
down_revision = '8bfe97bb0eee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_preference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pref_blog_published', sa.Boolean(), nullable=False, server_default=sa.true()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_preference', schema=None) as batch_op:
        batch_op.drop_column('pref_blog_published')

    # ### end Alembic commands ###
