"""add activity_log table

Revision ID: 41061e65f386
Revises: 4f5ead0f678a
Create Date: 2026-06-01 10:16:12.590180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '41061e65f386'
down_revision = '4f5ead0f678a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    tables = inspector.get_table_names()
    if 'activity_log' not in tables:
        op.create_table('activity_log',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('uuid', sa.String(length=36), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('action', sa.String(length=64), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('url', sa.String(length=512), nullable=True),
        sa.Column('method', sa.String(length=8), nullable=True),
        sa.Column('target_type', sa.String(length=32), nullable=True),
        sa.Column('target_id', sa.Integer(), nullable=True),
        sa.Column('target_uuid', sa.String(length=36), nullable=True),
        sa.Column('extra', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('activity_log', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_activity_log_action'), ['action'], unique=False)
            batch_op.create_index(batch_op.f('ix_activity_log_created_at'), ['created_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_activity_log_target_type'), ['target_type'], unique=False)
            batch_op.create_index(batch_op.f('ix_activity_log_user_id'), ['user_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_activity_log_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    tables = inspector.get_table_names()
    if 'activity_log' in tables:
        with op.batch_alter_table('activity_log', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_activity_log_uuid'))
            batch_op.drop_index(batch_op.f('ix_activity_log_user_id'))
            batch_op.drop_index(batch_op.f('ix_activity_log_target_type'))
            batch_op.drop_index(batch_op.f('ix_activity_log_created_at'))
            batch_op.drop_index(batch_op.f('ix_activity_log_action'))

        op.drop_table('activity_log')
    # ### end Alembic commands ###
