"""empty message

Revision ID: 4f5ead0f678a
Revises: 0b1c535cf9e3
Create Date: 2026-05-04 13:54:21.588819

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '4f5ead0f678a'
down_revision = '0b1c535cf9e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    cols = {c['name'] for c in inspector.get_columns('user')}
    if 'username' not in cols:
        with op.batch_alter_table('user', schema=None) as batch_op:
            batch_op.add_column(sa.Column('username', sa.String(length=64), nullable=True))
            batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
            batch_op.add_column(sa.Column('profile_picture', sa.String(length=256), nullable=True))
            batch_op.add_column(sa.Column('location', sa.String(length=128), nullable=True))
            batch_op.add_column(sa.Column('website_url', sa.String(length=256), nullable=True))
            batch_op.add_column(sa.Column('github_url', sa.String(length=256), nullable=True))
            batch_op.add_column(sa.Column('twitter_url', sa.String(length=256), nullable=True))
            batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
            batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))
            batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    cols = {c['name'] for c in inspector.get_columns('user')}
    if 'username' in cols:
        with op.batch_alter_table('user', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_user_username'))
            batch_op.drop_column('last_seen')
            batch_op.drop_column('created_at')
            batch_op.drop_column('twitter_url')
            batch_op.drop_column('github_url')
            batch_op.drop_column('website_url')
            batch_op.drop_column('location')
            batch_op.drop_column('profile_picture')
            batch_op.drop_column('bio')
            batch_op.drop_column('username')

    # ### end Alembic commands ###
