"""add title category level user_agent to activity_log

Revision ID: 67039fcea7d2
Revises: e8f1d47955ac
Create Date: 2026-06-22 13:26:09.617381

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '67039fcea7d2'
down_revision = 'e8f1d47955ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    cols = {c['name'] for c in inspector.get_columns('activity_log')}
    if 'title' not in cols:
        with op.batch_alter_table('activity_log', schema=None) as batch_op:
            batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))
            batch_op.add_column(sa.Column('category', sa.String(length=32), nullable=True))
            batch_op.add_column(sa.Column('level', sa.String(length=16), nullable=True))
            batch_op.add_column(sa.Column('user_agent', sa.String(length=256), nullable=True))
            batch_op.create_index(batch_op.f('ix_activity_log_category'), ['category'], unique=False)
            batch_op.create_index(batch_op.f('ix_activity_log_level'), ['level'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    cols = {c['name'] for c in inspector.get_columns('activity_log')}
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        if 'title' in cols:
            batch_op.drop_index(batch_op.f('ix_activity_log_level'))
            batch_op.drop_index(batch_op.f('ix_activity_log_category'))
            batch_op.drop_column('user_agent')
            batch_op.drop_column('level')
            batch_op.drop_column('category')
            batch_op.drop_column('title')

    # ### end Alembic commands ###
