"""activity log is_public icon

Revision ID: 7b2258988f53
Revises: 1db2c14335d3
Create Date: 2026-06-01 11:32:16.336752

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '7b2258988f53'
down_revision = '1db2c14335d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    cols = {c['name'] for c in inspector.get_columns('activity_log')}
    if 'is_public' not in cols:
        with op.batch_alter_table('activity_log', schema=None) as batch_op:
            batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False, server_default='false'))
            batch_op.add_column(sa.Column('icon', sa.String(length=64), nullable=True))
            batch_op.create_index(batch_op.f('ix_activity_log_is_public'), ['is_public'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    cols = {c['name'] for c in inspector.get_columns('activity_log')}
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        if 'is_public' in cols:
            batch_op.drop_index(batch_op.f('ix_activity_log_is_public'))
            batch_op.drop_column('icon')
            batch_op.drop_column('is_public')

    # ### end Alembic commands ###
