"""add external_links and BlogPostFile

Revision ID: 8bfe97bb0eee
Revises: 04ca95d888fc
Create Date: 2026-06-29 10:24:13.929404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bfe97bb0eee'
down_revision = '04ca95d888fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_post_file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['blog_post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_post_file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_post_file_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_post_file_uuid'), ['uuid'], unique=True)

    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_links', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_column('external_links')

    with op.batch_alter_table('blog_post_file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_post_file_uuid'))
        batch_op.drop_index(batch_op.f('ix_blog_post_file_post_id'))

    op.drop_table('blog_post_file')
    # ### end Alembic commands ###
