"""add workspace and rule status

Revision ID: 8c573ad2ff74
Revises: f068bccb2e74
Create Date: 2026-06-25 10:36:58.447850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '8c573ad2ff74'
down_revision = 'f068bccb2e74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    tables = inspector.get_table_names()
    if 'workspace' not in tables:
        op.create_table('workspace',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('uuid', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('icon', sa.String(length=50), nullable=False),
        sa.Column('color', sa.String(length=20), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('workspace', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_workspace_uuid'), ['uuid'], unique=True)

    if 'workspace_rule' not in tables:
        op.create_table('workspace_rule',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('workspace_id', sa.Integer(), nullable=False),
        sa.Column('rule_id', sa.Integer(), nullable=False),
        sa.Column('added_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('workspace_id', 'rule_id')
        )

    rule_cols = {c['name'] for c in inspector.get_columns('rule')}
    if 'status' not in rule_cols:
        with op.batch_alter_table('rule', schema=None) as batch_op:
            batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='draft'))
            batch_op.create_index(batch_op.f('ix_rule_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    rule_cols = {c['name'] for c in inspector.get_columns('rule')}
    if 'status' in rule_cols:
        with op.batch_alter_table('rule', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_rule_status'))
            batch_op.drop_column('status')

    tables = inspector.get_table_names()
    if 'workspace_rule' in tables:
        op.drop_table('workspace_rule')

    if 'workspace' in tables:
        with op.batch_alter_table('workspace', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_workspace_uuid'))

        op.drop_table('workspace')
    # ### end Alembic commands ###
