"""add gamification new metrics and user_badge table

Revision ID: 9bbf0463e0bb
Revises: 3d53cf4fb0ba
Create Date: 2026-09-11 17:41:34.546691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bbf0463e0bb'
down_revision = '3d53cf4fb0ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_badge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_key', sa.String(length=64), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'badge_key', name='uq_user_badge_user_key')
    )
    with op.batch_alter_table('user_badge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_badge_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('gamification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bundles_owned', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rule_tests_contributed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('attack_mappings_contributed', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gamification', schema=None) as batch_op:
        batch_op.drop_column('attack_mappings_contributed')
        batch_op.drop_column('rule_tests_contributed')
        batch_op.drop_column('bundles_owned')

    with op.batch_alter_table('user_badge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_badge_user_id'))

    op.drop_table('user_badge')
    # ### end Alembic commands ###
