"""add checked_by to report

Revision ID: a78167451235
Revises: 2320e80f2f0c
Create Date: 2026-06-24 11:19:56.594162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a78167451235'
down_revision = '2320e80f2f0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('checked_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['checked_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('checked_at')
        batch_op.drop_column('checked_by_id')

    # ### end Alembic commands ###
