"""increase user api_key length to 128

Revision ID: b4d9e79158a0
Revises: 67039fcea7d2
Create Date: 2026-06-24 09:45:28.162085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'b4d9e79158a0'
down_revision = '67039fcea7d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    user_cols = {c['name']: c for c in inspector.get_columns('user')}
    col_type = user_cols['api_key']['type'] if 'api_key' in user_cols else None
    if col_type is not None and isinstance(col_type, sa.VARCHAR) and (col_type.length is None or col_type.length < 128):
        with op.batch_alter_table('user', schema=None) as batch_op:
            batch_op.alter_column('api_key',
                   existing_type=sa.VARCHAR(length=60),
                   type_=sa.String(length=128),
                   existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    user_cols = {c['name']: c for c in inspector.get_columns('user')}
    col_type = user_cols['api_key']['type'] if 'api_key' in user_cols else None
    if col_type is not None and isinstance(col_type, sa.VARCHAR) and col_type.length is not None and col_type.length >= 128:
        with op.batch_alter_table('user', schema=None) as batch_op:
            batch_op.alter_column('api_key',
                   existing_type=sa.String(length=128),
                   type_=sa.VARCHAR(length=60),
                   existing_nullable=True)

    # ### end Alembic commands ###
