"""fix blog_post_rule FK to rule.id

Revision ID: b6af94f28712
Revises: 26c14494c172
Create Date: 2026-06-29 10:01:01.668267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6af94f28712'
down_revision = '26c14494c172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post_rule', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('blog_post_rule_rule_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'rule', ['rule_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post_rule', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('blog_post_rule_rule_id_fkey'), 'new_rule', ['rule_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
