"""add notification_preference table and new notif types

Revision ID: bb02dd519fd6
Revises: b4d9e79158a0
Create Date: 2026-06-24 09:55:15.510736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb02dd519fd6'
down_revision = 'b4d9e79158a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preference',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pref_follow_new_rule', sa.Boolean(), nullable=False),
    sa.Column('pref_follow_new_bundle', sa.Boolean(), nullable=False),
    sa.Column('pref_follow_new_comment', sa.Boolean(), nullable=False),
    sa.Column('pref_rule_comment', sa.Boolean(), nullable=False),
    sa.Column('pref_bundle_comment', sa.Boolean(), nullable=False),
    sa.Column('pref_job_done', sa.Boolean(), nullable=False),
    sa.Column('pref_proposal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_preference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_preference_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_preference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_preference_user_id'))

    op.drop_table('notification_preference')
    # ### end Alembic commands ###
