"""add proposal_comment, proposal_accepted, comment_reply to notification_preference

Revision ID: dc9725647a6f
Revises: bb02dd519fd6
Create Date: 2026-06-24 10:01:30.355035

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'dc9725647a6f'
down_revision = 'bb02dd519fd6'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = inspect(bind)
    cols = {c['name'] for c in inspector.get_columns('notification_preference')}
    if 'pref_proposal_comment' not in cols:
        with op.batch_alter_table('notification_preference', schema=None) as batch_op:
            batch_op.add_column(sa.Column('pref_proposal_comment',  sa.Boolean(), nullable=False, server_default=sa.true()))
            batch_op.add_column(sa.Column('pref_proposal_accepted', sa.Boolean(), nullable=False, server_default=sa.true()))
            batch_op.add_column(sa.Column('pref_comment_reply',     sa.Boolean(), nullable=False, server_default=sa.true()))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    cols = {c['name'] for c in inspector.get_columns('notification_preference')}
    with op.batch_alter_table('notification_preference', schema=None) as batch_op:
        if 'pref_comment_reply' in cols:
            batch_op.drop_column('pref_comment_reply')
        if 'pref_proposal_accepted' in cols:
            batch_op.drop_column('pref_proposal_accepted')
        if 'pref_proposal_comment' in cols:
            batch_op.drop_column('pref_proposal_comment')

    # ### end Alembic commands ###
