"""add blog models

Revision ID: e43f7931ee0c
Revises: 2337748f9558
Create Date: 2026-06-29 08:47:11.570218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e43f7931ee0c'
down_revision = '2337748f9558'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('share_key', sa.String(length=64), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('cve_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_post_is_public'), ['is_public'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_post_share_key'), ['share_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_post_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_blog_post_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_post_uuid'), ['uuid'], unique=True)

    op.create_table('blog_post_attack',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('technique_id', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['blog_post.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_post_attack', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_post_attack_post_id'), ['post_id'], unique=False)

    op.create_table('blog_post_rule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['blog_post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['new_rule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_post_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_post_rule_post_id'), ['post_id'], unique=False)

    op.create_table('blog_post_tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['blog_post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_post_tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_post_tag_post_id'), ['post_id'], unique=False)

    op.create_table('blog_post_bundle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('bundle_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bundle_id'], ['bundle.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['blog_post.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_post_bundle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_post_bundle_post_id'), ['post_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post_bundle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_post_bundle_post_id'))

    op.drop_table('blog_post_bundle')
    with op.batch_alter_table('blog_post_tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_post_tag_post_id'))

    op.drop_table('blog_post_tag')
    with op.batch_alter_table('blog_post_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_post_rule_post_id'))

    op.drop_table('blog_post_rule')
    with op.batch_alter_table('blog_post_attack', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_post_attack_post_id'))

    op.drop_table('blog_post_attack')
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_post_uuid'))
        batch_op.drop_index(batch_op.f('ix_blog_post_user_id'))
        batch_op.drop_index(batch_op.f('ix_blog_post_slug'))
        batch_op.drop_index(batch_op.f('ix_blog_post_share_key'))
        batch_op.drop_index(batch_op.f('ix_blog_post_is_public'))

    op.drop_table('blog_post')
    # ### end Alembic commands ###
