"""add user_config and custom_theme tables

Revision ID: e8f1d47955ac
Revises: c7a1f3e2d9b5
Create Date: 2026-06-22 11:57:22.486591

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'e8f1d47955ac'
down_revision = 'c7a1f3e2d9b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    tables = inspector.get_table_names()
    if 'custom_theme' not in tables:
        op.create_table('custom_theme',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('uuid', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.Column('css_key', sa.String(length=64), nullable=False),
        sa.Column('icon', sa.String(length=64), nullable=False),
        sa.Column('is_dark', sa.Boolean(), nullable=False),
        sa.Column('is_builtin', sa.Boolean(), nullable=False),
        sa.Column('is_public', sa.Boolean(), nullable=False),
        sa.Column('css_vars', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('deleted_by', sa.Integer(), nullable=True),
        sa.Column('meta', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('css_key'),
        sa.UniqueConstraint('uuid')
        )

    if 'user_config' not in tables:
        op.create_table('user_config',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('uuid', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('meta', sa.JSON(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('theme', sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id'),
        sa.UniqueConstraint('uuid')
        )

    existing_indexes = {ix['name'] for ix in inspector.get_indexes('comment_v2')}
    existing_unique = {uc['name'] for uc in inspector.get_unique_constraints('comment_v2')}
    # Guard: only run if the new indexes don't exist yet (migration not yet applied).
    # ix_comment_v2_object_id is a new index created by this migration.
    if 'ix_comment_v2_object_id' not in existing_indexes:
        with op.batch_alter_table('comment_v2', schema=None) as batch_op:
            if 'comment_v2_uuid_key' in existing_unique:
                batch_op.drop_constraint(batch_op.f('comment_v2_uuid_key'), type_='unique')
            if 'ix_comment_v2_object' in existing_indexes:
                batch_op.drop_index(batch_op.f('ix_comment_v2_object'))
            if 'ix_comment_v2_uuid' in existing_indexes:
                batch_op.drop_index(batch_op.f('ix_comment_v2_uuid'))
            batch_op.create_index(batch_op.f('ix_comment_v2_uuid'), ['uuid'], unique=True)
            batch_op.create_index(batch_op.f('ix_comment_v2_object_id'), ['object_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_comment_v2_object_type'), ['object_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_indexes = {ix['name'] for ix in inspector.get_indexes('comment_v2')}
    existing_unique = {uc['name'] for uc in inspector.get_unique_constraints('comment_v2')}
    # Guard: only run if the new indexes are still present (migration was applied).
    if 'ix_comment_v2_object_id' in existing_indexes:
        with op.batch_alter_table('comment_v2', schema=None) as batch_op:
            if 'ix_comment_v2_object_type' in existing_indexes:
                batch_op.drop_index(batch_op.f('ix_comment_v2_object_type'))
            if 'ix_comment_v2_object_id' in existing_indexes:
                batch_op.drop_index(batch_op.f('ix_comment_v2_object_id'))
            if 'ix_comment_v2_uuid' in existing_indexes:
                batch_op.drop_index(batch_op.f('ix_comment_v2_uuid'))
            batch_op.create_index(batch_op.f('ix_comment_v2_uuid'), ['uuid'], unique=False)
            batch_op.create_index(batch_op.f('ix_comment_v2_object'), ['object_type', 'object_id'], unique=False)
            if 'comment_v2_uuid_key' not in existing_unique:
                batch_op.create_unique_constraint(batch_op.f('comment_v2_uuid_key'), ['uuid'], postgresql_nulls_not_distinct=False)

    tables = inspector.get_table_names()
    if 'user_config' in tables:
        op.drop_table('user_config')
    if 'custom_theme' in tables:
        op.drop_table('custom_theme')
    # ### end Alembic commands ###
